FROM hyperledger/sawtooth-intkey-tp-python:1.0

RUN apt-get update && apt-get install -y python3-cryptography python3-sawtooth-*

#install protobuf protoc
#RUN apt-get install -y curl zip
#RUN curl -OL https://github.com/google/protobuf/releases/download/v3.2.0/protoc-3.2.0-linux-x86_64.zip
#RUN unzip protoc-3.2.0-linux-x86_64.zip -d protoc3
#RUN mv protoc3/bin/* /usr/local/bin/
#RUN mv protoc3/include/* /usr/local/include/
